packages:
  role: !include managed-s3.yaml
  installation: !include devices/test.yaml

substitutions:
  name: "passion-wave-managed-2-s3"
  friendly_name: "PassionWave RotaryKnob 2"
  project_name: "passion-wave.rotaryknob-s3"
  project_version: "3.0.1-beta.8"
  media_debug_topic: "passion_wave/managed_2_s3/media/debug"
  managed_fallback_ap_ssid: "PW Managed 2 S3"
  responsive_power_policy_enabled: "true"
  responsive_power_idle_ms: "3000"
  battery_deep_sleep_after_inactivity_ms: "75000"

esphome:
  build_path: build/managed_test_s3
