packages:
  role: !include managed-esp32.yaml
  installation: !include devices/test.yaml

substitutions:
  name: "passion-wave-managed-2-bridge"
  friendly_name: "PassionWave RotaryKnob Bridge 2"
  managed_fallback_ap_ssid: "PW Managed 2 Bridge"
  responsive_power_policy_enabled: "true"
  responsive_power_idle_ms: "3000"

esphome:
  build_path: build/managed_test_esp32
  project:
    name: "passion-wave.rotaryknob-bridge"
    version: "3.0.1-beta.15"
