packages:
  role: !include managed-s3.yaml
  installation: !include devices/test.yaml

substitutions:
  name: "passion-wave-managed-2-s3"
  friendly_name: "PassionWave Rotaryknob 2"
  project_name: "passion-wave.rotaryknob-s3"
  project_version: "3.0.0-beta.12"
  media_debug_topic: "passion_wave/managed_2_s3/media/debug"
  managed_fallback_ap_ssid: "PW Managed 2 S3"

esphome:
  build_path: build/managed_test_s3
