packages:
  role: !include managed-esp32.yaml
  installation: !include devices/production.yaml

substitutions:
  name: "passion-wave-managed-1-bridge"
  friendly_name: "PassionWave Rotaryknob Bridge"
  managed_fallback_ap_ssid: "PW Managed 1 Bridge"

esphome:
  build_path: build/managed_production_esp32
  project:
    name: "passion-wave.rotaryknob-bridge"
    version: "3.0.0-beta.14"
